# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'FacebookPopSwift2.0' do

pod 'pop', '~> 1.0'
pod 'Parse'

end

target 'FacebookPopSwift2.0Tests' do

end

target 'FacebookPopSwift2.0UITests' do

end

